[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
pythonpath = ..
filterwarnings =
    ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset:pytest.PytestDeprecationWarning
    ignore:Support for class-based `config` is deprecated, use ConfigDict instead:DeprecationWarning
    ignore:Using extra keyword arguments on `Field` is deprecated:DeprecationWarning
    ignore::DeprecationWarning:jose.jwt
